apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # namespace.yaml is managed by redpanda-operator kustomization
  # operator.yaml is managed by redpanda-operator kustomization
  - rbac.yaml
  - cluster.yaml
  - console.yaml
