apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gotk-components.yaml
  - gitrepository.yaml
  - infrastructure-kustomization.yaml
  - redpanda-operator-kustomization.yaml
  - redpanda-cluster-kustomization.yaml

