apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redpanda-operator
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/demo/infrastructure/redpanda-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: integration-platform
  timeout: 5m

