apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redpanda-cluster
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/demo/infrastructure/redpanda-cluster
  prune: true
  dependsOn:
    - name: redpanda-operator
  sourceRef:
    kind: GitRepository
    name: integration-platform
  timeout: 10m

